resolver: lts-12.25

packages:
  - 'tensile-dimensions'
  - 'tensile-tensorflow'
extra-deps:
  - haskell/tensorflow
  - haskell/tensorflow-core-ops
  - haskell/tensorflow-logging
  - haskell/tensorflow-mnist
  - haskell/tensorflow-mnist-input-data
  - haskell/tensorflow-opgen
  - haskell/tensorflow-proto
  - haskell/tensorflow-records
  - haskell/tensorflow-records-conduit
  - haskell/tensorflow-test
  - combinat-0.2.9.0
  - dimensions-1.0.1.1
  - proto-lens-protobuf-types-0.3.0.1
  - proto-lens-0.3.1.0
  - proto-lens-protoc-0.3.1.2
  - snappy-0.2.0.2
  - snappy-framing-0.1.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
