resolver: lts-11.22

packages:
  - 'tensile'
  - 'tensile-dimensions'
  - 'tensile-signatures'
  - 'tensile-tensorflow'
extra-deps:
  - snappy-0.2.0.2
  - snappy-framing-0.1.1
  - tensorflow-0.2
  - tensorflow-core-ops-0.2.0.0
  - tensorflow-logging-0.2.0.0
  - tensorflow-mnist-0.1.0.0
  - tensorflow-opgen-0.2.0.0
  - tensorflow-ops-0.2.0.0
  - tensorflow-proto-0.2
  - tensorflow-records-0.1.0.0
  - tensorflow-records-conduit-0.1.0.0
  - tensorflow-test-0.1.0.0
# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
